export const ADD_RECIPE = 'ADD_RECIPE'
export const FILTER_BY_INGREDIENTS = 'FILTER_BY_INGREDIENTS'
export const FILTER_BY_TITLE = 'FILTER_BY_TITLE'
export const TOGGLE_FILTER_TYPE = 'TOGGLE_FILTER_TYPE'
